name: Run Tests

on:
  push:
    paths:
      - 'src/**'

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Use Node.js
        uses: actions/setup-node@v1

      - name: NPM Install
        run: npm ci

      - name: Run NPM Tests
        run: npm test
